# Generated by Django 2.0 on 2017-12-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='note',
            name='excerpt',
            field=models.TextField(default='this is an excerpt'),
            preserve_default=False,
        ),
    ]
