# Generated by Django 2.0 on 2017-12-06 20:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0002_auto_20171206_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='notebook',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
